### ISSUE TITLE
Release build_*.jl file

### ISSUE THREAD

**Issue by JoshChristie** [twadleigh/BoostBuilder#1]
Thanks for putting this package together!

Just wondering if you could configure the release to include the `build_BoostBuilder.jl` file?

An example would be something along the lines of what's here I guess https://github.com/JuliaPackaging/JuliaBuilder/releases

**Comment by twadleigh** [comment]
Thanks for your help on this. Now I just need to reenable all the platforms I disabled hoping to get the build to succeed.
